### PR TITLE
Ported to Python 3; Updates to README to reflect package requirements…

### PR DESCRIPTION
**Pull request by Bruce1979**
…, usage instructions and other tweaks; inclusion of requirements.txt to assist with installation; added -n switch to specify number of slots; Minor output spacing/tweaks/fixes; change to slot output to allow for variants that support adjacent placement in both inner and outer rows.

### CODE REVIEW

**Comment by timur-tabi** [comment]
Hmmmm.   I'm not crazy about the conversion to Python 3, as I don't use it.  Does your patch break compatibility with Python 2?

**Comment by Bruce1979** [comment]
Hmm... apparently not (although it does change the package requirements slightly, since pysvg != pysvg-py3 (but that's the only difference). If you were to install pysvg under python 2 and pysvg-py3 under python 3, it should work for both versions.

Output changes slightly (as in, Python 3 prints a couple of blank lines, whereas Python 2 prints a couple of empty tuples), but otherwise I appear to get the same result using both. Conveniently, both the pysvg and pysvg-py3 packages use the same import statements

**Comment by Bruce1979** [comment]
Ok, I've now updated the branch so that it should work across both py2 and py3. I've tested in a clean virtualenv for version 3.5 and 2.7, and both behaved consistently.

**Comment by Bruce1979** [comment]
I've been thinking that if you'd like to keep the Python 2 fork independent of Python 3, one other approach we could follow is that I keep my for completely independent and write it for Python 3 only, and we use the README files in each project to cross-reference the other projects for each major version of Python. I could then continue to develop features independently on the Py3 fork if you'd rather not incorporate them into the Py2 fork.

The most current version of the source on this pull request, though, should be compatible with both versions. I'm happy to make minor edits if necessary to get them merged into this repo.

**Comment by timur-tabi** [comment]
I was thinking the same thing.  I haven't had a chance to review your code.  My concern is that since I don't work with Python 3, I might inadvertently break it with some Python 2-only change.

But give me a chance to review and test your changes before I make a decision.  Do you have plans for a lot of other changes?

**Comment by Bruce1979** [comment]
At this stage, not really - I've been thinking about potentially having some kind of more customisable option for things like uneven column widths, but haven't really worked out exactly what that would look like due to the need for additional dividers. I'm pretty happy with the current state being the new stable state.

**Comment by Bruce1979** [comment]
I'm going to assume, since there's been no activity on this PR for a while, that you've decided you want to keep this branch separate? If so, do you mind if I continue to develop independently for Python 3? I'll keep the original attribution for your code, but future iterations may lose compatibility with Python 2 if I develop it separately, since I probably won't test for it (although I doubt it'll introduce compatibility issues given the libraries in use are pretty lean).

**Comment by timur-tabi** [comment]
Sorry about that, I've been distracted with other things.  I think it makes sense for you to keep your own fork.  That way, you don't have to wait for me to approve anything.  If you add any features that I like, I'll either back-port them or just use your version.

**Pull request closed without merging**
